name: aoc2024
description: Advent Of Code 2024
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
